project:
  type: website
  output-dir: docs

website:
  title: "Niki's NM2207"
  favicon: "hehe.png"
  navbar:
    left:
      - href: index.qmd
        text: About me
        icon: house
      - href: testing.qmd
        text: My weekly R submissions
        icon: body-text
    right:
      - icon: github
        href: https://github.com/nokid0ki?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/niki-hartono/
    
format:
  html:
    theme:
      light: [morph,test.scss]
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual


