project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  title: "Niki's NM2207"
  navbar:
    left:
      - href: index.qmd
        text: About me
        icon: house
      - href: testing.qmd
        text: My weekly R submissions
        icon: body-text
    right:
      - icon: github
        href: https://github.com/nokid0ki/nm2207wuhu
    
format:
  html:
    theme:
      light: [morph,test.scss]
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual


