project:
  type: website
  output-dir: docs

website:
  title: "Niki's NM2207"
  favicon: "hehe.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house
      - href: testing.qmd
        text: Weekly R submissions
        icon: body-text
      - href: project.qmd
        text: Final project
        icon: geo-alt-fill
    right:
      - icon: github
        href: https://github.com/nokid0ki?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/niki-hartono/
    
format:
  html:
    theme:
      light: [morph,test.scss]
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual


